on:
  release:
    types: [created, published]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        compress_assets: auto
        md5sum: false
        retry: 3
        ldflags: "-s -w"
        goversion: "https://dl.google.com/go/go1.22.8.linux-amd64.tar.gz"
        project_path: "./helloserver_http_server"
        binary_name: "helloserver_http_server"

    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        compress_assets: auto
        md5sum: false
        retry: 3
        ldflags: "-s -w"
        goversion: "https://dl.google.com/go/go1.22.8.linux-amd64.tar.gz"
        project_path: "./helloserver_grpc_server"
        binary_name: "helloserver_grpc_server"
